Repository option26/quarantine-hero, pull requests merged in 2020-04, with the labels that each got.

#199 Update of press page
  src/App.jsx
  src/assets/aktion_mensch.jpg
  src/assets/berliner_morgenpost.jpg
  src/assets/bigfm.jpg
  src/assets/br.jpg
  src/assets/business_insider.jpg
  src/assets/cosmo.jpg
  src/assets/cosmopolitan.jpg
  src/assets/deutschlandfunk.jpg
  src/assets/focus_online.jpg
  src/assets/greenpeace_magazin.jpg
  src/assets/hr.jpg
  src/assets/rpr1.jpg
  src/assets/sat1.jpg
  src/assets/sat1_regional.jpg
  src/assets/sueddeutsche_zeitung.jpg
  src/assets/utopia.jpg
  src/assets/vogue.jpg
  src/assets/wdr.jpg
  src/assets/welt.jpg
  src/assets/youfm.jpg
  src/assets/zdf.jpg
  src/components/Sidebar.jsx
  src/views/Press.jsx
Labels: quick-win

#231 Catch errors when parsing entries
  src/components/EntryMap.jsx
Labels: quick-win

#225 Enhancement/221 refactor navigation
  src/App.jsx
  src/components/Footer.jsx
  src/components/ScrollToTop.jsx
  src/views/AskForHelp.jsx
  src/views/CompleteOfferHelp.jsx
  src/views/DSGVO.jsx
  src/views/FAQ.jsx
  src/views/Impressum.jsx
  src/views/Main.jsx
  src/views/NotFound.jsx
  src/views/NotifyMe.jsx
  src/views/OfferHelp.jsx
  src/views/Overview.jsx
  src/views/Press.jsx
  src/views/Security.jsx
  src/views/Signin.jsx
  src/views/Signup.jsx
  src/views/Success.jsx
  src/views/SuccessOffer.jsx
  src/views/VerifyEmail.jsx
Labels: quick-win

#229 Enhancement/66 tighten eslint rules
  .eslintrc.json
  src/App.jsx
  src/components/ArrowDown.jsx
  src/components/DesktopMenu.jsx
  src/components/EntryList.jsx
  src/components/EntryMap.jsx
  src/components/LocationInput.jsx
  src/components/OnePagers.jsx
  src/components/Responses.jsx
  src/components/entry/Entry.jsx
  src/styles/Map.css
  src/views/CompleteOfferHelp.jsx
  src/views/Dashboard.jsx
  src/views/FAQ.jsx
  src/views/Impressum.jsx
  src/views/OfferHelp.jsx
  src/views/Press.jsx
Labels: needs consideration

#153 Feature/solved issues
  cypress/integration/dashboard.spec.js
  cypress/util/createAskForHelpPosting.js
  cypress/util/createResponseForPosting.js
  cypress/util/loginVerifiedUser.js
  cypress/util/removeExistingAskForHelpEntries.js
  package.json
  public/locales/de/translation.json
  src/assets/questionmark.svg
  src/components/EntryList.jsx
  src/components/EntryMap.jsx
  src/components/LocationInput.jsx
  src/components/MailInput.jsx
  src/components/Popup.jsx
  src/components/Responses.jsx
  src/components/entry/Entry.jsx
  src/index.jsx
  src/services/loadResponses.js
  src/styles/App.css
  src/styles/index.css
  src/util/parseDoc.js
  src/views/AskForHelp.jsx
  src/views/Dashboard.jsx
  src/views/OfferHelp.jsx
  src/views/Success.jsx
  src/views/SuccessOffer.jsx
  tailwind.config.js
  yarn.lock
Labels: needs consideration

#257 Bug fix: updated the logo inside the map
  src/components/EntryMap.jsx
Labels: bug, priority-high

#267 Fixed wording at several places
  CONTRIBUTING.md
  MAINTAINERS.md
  README.md
  firebase/functions/index.js
  public/index.html
  public/locales/de/translation.json
  qhero_icon.png
  src/views/Press.jsx
  src/views/VerifyEmail.jsx
Labels: quick-win
