Repository option26/quarantine-hero, pull requests merged in 2020-03, with the labels that each got.

#179 Disable i18next debug logging
  src/i18n.js
Labels: quick-win

#178 Use correct OnePagers component on overview
  src/components/OnePagers.jsx
  src/views/Main.jsx
  src/views/Overview.jsx
Labels: quick-win

#174 Ignore cypress screenshots and videos in git
  .gitignore
Labels: quick-win

#163 Add error page (#156)
  .gitignore
  public/locales/de/translation.json
  src/App.jsx
  src/assets/icon_baby.svg
  src/assets/icon_barbecue.svg
  src/assets/icon_dog.svg
  src/assets/icon_iron.svg
  src/assets/icon_propose.svg
  src/assets/icon_sauna.svg
  src/assets/icon_saw.svg
  src/assets/icon_taste.svg
  src/assets/icon_vacuum.svg
  src/components/UnderlinedHeader.jsx
  src/styles/App.css
  src/styles/index.css
  src/views/NotFound.jsx
  yarn.lock
Labels: quick-win

#177 Feature/error reporting
  .env
  .env.development
  package.json
  src/App.jsx
  src/components/FilteredList.jsx
  src/components/LocationInput.jsx
  src/views/NotifyMe.jsx
Labels: quick-win

#168 Feature/separate login form
  .eslintrc.json
  cypress/integration/landingpage.spec.js
  cypress/integration/signin.spec.js
  cypress/integration/signup.spec.js
  public/locales/de/translation.json
  src/App.jsx
  src/components/Entry.jsx
  src/components/MailInput.jsx
  src/components/Sidebar.jsx
  src/views/AskForHelp.jsx
  src/views/Dashboard.jsx
  src/views/Main.jsx
  src/views/NotifyMe.jsx
  src/views/OfferHelp.jsx
  src/views/Signin.jsx
  src/views/Signup.jsx
Labels: waiting for feedback

#185 Fix layout of responses on narrow screens (e.g. mobile)
  src/components/Responses.jsx
Labels: quick-win

#192 fix delete for ask-for-help documents with updated firebase functions
  src/components/Entry.jsx
Labels: bug, priority-high

#193 Updated FAQ component with a new logic and new content
  public/locales/de/translation.json
  src/views/FAQ.jsx
Labels: priority-medium, quick-win
