Repository option26/quarantine-hero, pull requests merged in 2020-05, with the labels that each got.

#271 Fix grammatical case of German timestamps for entries and responses
  public/locales/de/translation.json
  src/components/Responses.jsx
  src/components/entry/Entry.jsx
Labels: quick-win

#233 Feature/127 address clickable
  src/components/EntryList.jsx
  src/components/LocationInput.jsx
  src/components/entry/Entry.jsx
  src/styles/index.css
Labels: needs consideration

#280 Navigate to clear search
  src/components/EntryList.jsx
Labels: quick-win

#278 Add function to serve hotline numbers from google sheet
  firebase/functions/hotline.js
  firebase/functions/index.js
  firebase/functions/package-lock.json
  firebase/functions/package.json
Labels: enhancement, priority-high

#262 Add askForHelpId to sendgrid dynamic template variables for offer-help
  firebase/functions/index.js
Labels: quick-win

#270 Own account management
  cypress/util/createAskForHelpPosting.js
  public/locales/de/translation.json
  src/App.jsx
  src/components/StatusIndicator.jsx
  src/components/loader/Loader.jsx
  src/util/buildHash.js
  src/views/CompleteOfferHelp.jsx
  src/views/HandleEmailAction.jsx
  src/views/NotifyMe.jsx
  src/views/Success.jsx
Labels: needs consideration

#283 Hotfix/add hotline timezone support
  firebase/functions/hotline.js
  firebase/functions/package-lock.json
  firebase/functions/package.json
Labels: priority-high, quick-win

#227 Made mobile the first test case for cypress and updated the github ac…
  .github/workflows/build-firebase.sh
  .github/workflows/build-frontend.sh
  .github/workflows/deploy-firebase.sh
  .github/workflows/deploy-frontend.sh
  .github/workflows/deploy.yaml
  .github/workflows/pr.yml
  cypress-desktop.json
  cypress.json
  cypress/integration/landingpage.spec.js
  firebase/functions/package.json
  package.json
  src/App.jsx
  src/components/Sidebar.jsx
Labels: waiting for feedback

#296 Fixing deployment action
  .github/workflows/deploy.yaml
Labels: bug, priority-high

#295 Updated international signup pages
  public/assets/signUp/quarantaenehelden_a_albanian.pdf
  public/assets/signUp/quarantaenehelden_a_arabic.pdf
  public/assets/signUp/quarantaenehelden_a_bulgarian.pdf
  public/assets/signUp/quarantaenehelden_a_chinese_simple.pdf
  public/assets/signUp/quarantaenehelden_a_chinese_trad.pdf
  public/assets/signUp/quarantaenehelden_a_croatian.pdf
  public/assets/signUp/quarantaenehelden_a_french.pdf
  public/assets/signUp/quarantaenehelden_a_greek.pdf
  public/assets/signUp/quarantaenehelden_a_hungarian.pdf
  public/assets/signUp/quarantaenehelden_a_italian.pdf
  public/assets/signUp/quarantaenehelden_a_polish.pdf
  public/assets/signUp/quarantaenehelden_a_portuguese.pdf
  public/assets/signUp/quarantaenehelden_a_romanian.pdf
  public/assets/signUp/quarantaenehelden_a_russian.pdf
  public/assets/signUp/quarantaenehelden_a_spanish.pdf
  public/assets/signUp/quarantaenehelden_a_turkish.pdf
  public/assets/signUp/quarantaenehelden_a_ukrainian.pdf
  public/assets/signUp/quarantaenehelden_a_vietnamese.pdf
Labels: priority-high, quick-win

#277 Delete account feature
  firebase/functions/index.js
  firebase/functions/utils.js
  public/locales/de/translation.json
  src/App.jsx
  src/components/Responses.jsx
  src/views/CompleteNotification.jsx
  src/views/Dashboard.jsx
  src/views/NotifyMe.jsx
Labels: needs consideration
